### ISSUE TITLE
Broken a layout when focus outside a slide contents on Firefox

### ISSUE THREAD

**Issue by kubosho** [hiroppy/fusuma#115] opened 2019-06-24 16:36 UTC
## About

Broken a layout when focus outside a slide contents.

## Screenshot

![ZAsSZXglgH](https://user-images.githubusercontent.com/430267/60036148-7f5f2900-96e9-11e9-8af1-2f63d853c34c.gif)

## Reproduce

1. Open https://hiroppy.github.io/fusuma/intro on Firefox
2. Press the tab key several times

## Expected behavior

Not broken layout.

## Environment

Firefox Nightly 69.0a1 (2019-06-24) / Windows 10

**Comment by hiroppy** [comment] 2019-06-25 00:53
Thank you. I'll investigate this issue.

**Comment by hiroppy** [comment] 2019-06-25 11:20
I can't reproduce it. I'll try to use Firefox Nightly version...

```
Firefox: 67.0.4 (64-bit)
Mac: 10.14.5 (18F132)
```

**Comment by kubosho** [comment] 2019-06-25 11:35
I can't reproduce too on `macOS 10.14.5 / Firefox 67.0.4 and Nightly`. However I found can not keyboard focus on slide contents.
![2019-06-25 20-32-30 2019-06-25 20_34_32](https://user-images.githubusercontent.com/430267/60095070-ae78a780-9788-11e9-9814-d5f6fea08e40.gif)

**Comment by hiroppy** [comment] 2019-06-25 22:53
fm, this action seems to work on Chrome, but doesn't seem to work on firefox.

**Comment by arayaryoma** [comment] 2020-01-03 20:24
That is a default behavior of Firefox for mac. You should configure accessibility settings by yourself.

See also:
- https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/accessibility.tabfocus
- https://a11yproject.com/posts/macos-browser-keyboard-navigation/

**Comment by hiroppy** [comment] 2020-01-05 04:06
Thank you for answering! I'll close this issue.

**Closed by hiroppy** 2020-01-05 04:06 UTC
